### PR TITLE
Revoke site resource when pod vm creation is failed

### PR DESCRIPTION
**Pull request by kimeunju108**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it:**
This PR proposes to withdraw site (cluster) resource allocated to a pod when the pod's vm creation is failed.

**Which issue(s) this PR fixes:**
Fixes #286

**Special notes for your reviewer:**

**Does this PR introduce a user-facing change?:**
NONE

**How to test?:**
~/go/src/k8s.io/arktos$./hack/globalscheduler/globalscheduler-up.sh
open a new terminal
cd ~/go/src/k8s.io/arktos/globalscheduler/test/yaml
kubectl apply -f sample_6_clusters.yaml
kubectl apply -f sample_2_schedulers.yaml
kubectl apply -f sample_2_distributors.yaml
kubectl apply -f sample_2_dispatchers.yaml
kubectl apply -f sample_6_pods.yaml
kubectl get pods

### CODE REVIEW

**Comment by jshaofuturewei** [comment]
Is it a new PR? I have not found any previous comments.

**Comment by kimeunju108** [comment]
> Is it a new PR? I have not found any previous comments.

Yes, The PR 289 had an issue to update as we discussed last week. I could not update the same PR.
Your reviews are in the follwoing link and I answered most of them.
https://github.com/CentaurusInfra/global-resource-scheduler/pull/289

**Comment by jshaofuturewei** [comment]
> > Is it a new PR? I have not found any previous comments.
> 
> Yes, this is new PR with #298. The original PR 289 had an issue to update in CICD pass as we discussed last week. I could not update the same PR.
> Your reviews are in the follwoing link and I answered most of them.
> #289

Please reopen the #289 and its CICD issue has been resolved. My PR #288  works total fine now.

**Comment by kimeunju108** [comment]
> > > Is it a new PR? I have not found any previous comments.
> > 
> > 
> > Yes, this is new PR with #298. The original PR 289 had an issue to update in CICD pass as we discussed last week. I could not update the same PR.
> > Your reviews are in the follwoing link and I answered most of them.
> > #289
> 
> Please reopen the #289 and its CICD issue has been resolved. My PR #288 works total fine now.

I tried to reopen but it is not possible unfortumnately. open button is inactivated.

**Pull request closed without merging**
